### PR TITLE
Changes to JASPI PR from review.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
@janbartel can you please do a final review these changes here before they are merged into the main PR.

### CODE REVIEW

**Review by janbartel — CHANGES_REQUESTED** [review]
Line 42 isAvailable() should check for a `org.eclipse.jetty.jaspi.` class being available - if it's not this isAvailable() should return false (luckily currently the JaspiConfiguration doesn't happen to do anything). It's ok to hide the `jakarta.security.auth.message.` package in the constructor (just hides the jaspi api that could be on the server path from the webapp, the webapp could always provide its own copy if it wants to do something jaspi-ish itself).

**Comment by lachlan-roberts** [comment]
@janbartel I have updated the `JaspiConfiguration.isAvailible` to check `org.eclipse.jetty.security.jaspi.JaspiAuthenticator` instead.

**Comment by lachlan-roberts** [comment]
@janbartel this is ready for review.

**Review by janbartel — APPROVED** [review]
Looking good! Thanks @frode-carlsen for your efforts to get this updated, and @lachlan-roberts for getting it over the line.

**Pull request merged**
